### ISSUE TITLE
MYSQL-Error

### ISSUE THREAD

**Issue by fmoelder** [i-doit/scripts#38]
Hi,

on an fresh Debian 12 installation the fork-script from Nitair is running into a mySQL-Error:

ERROR 1356 (HY000) at line 1: View 'mysql.user' references invalid table(s) or column(s) or function(s) or definer/invoker of view lack rights to use them
SQL statement failed
Operation failed. Please check what is wrong and try again.

With kind regards
Frank

**Comment by MichaelOv** [comment]
Hey @fmoelder,

maybe because i-doit does not support MariaDB 10.11, which is included in Debian 12.
See the [System Requirements](https://kb.i-doit.com/en/installation/system-requirements.html)

Thats also why we did not add Debian 12 yet, MariaDB 10.11 support is planned for i-doit v30.
V30 is planned to be released in next month (April).
